"""create pcb units table

Revision ID: 43225ffdf58e
Revises: c9ac8354e3b5
Create Date: 2026-08-21 10:57:58.202801

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43225ffdf58e'
down_revision: Union[str, Sequence[str], None] = 'c9ac8354e3b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pcb_units',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('serial_number', sa.String(length=100), nullable=False),
    sa.Column('production_order_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'IN_PRODUCTION', 'PASSED', 'FAILED', 'REWORK', name='pcb_unit_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['production_order_id'], ['production_orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pcb_units_production_order_id'), 'pcb_units', ['production_order_id'], unique=False)
    op.create_index(op.f('ix_pcb_units_serial_number'), 'pcb_units', ['serial_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pcb_units_serial_number'), table_name='pcb_units')
    op.drop_index(op.f('ix_pcb_units_production_order_id'), table_name='pcb_units')
    op.drop_table('pcb_units')
    # ### end Alembic commands ###
