"""add material lots and pcb shifts

Revision ID: 9be507e2c74b
Revises: 325f538cc4ca
Create Date: 2026-08-25 09:41:53.085403

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9be507e2c74b'
down_revision: Union[str, Sequence[str], None] = '325f538cc4ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    shift_type_enum = sa.Enum(
        "DAY",
        "NIGHT",
        name="shift_type",
    )
    shift_type_enum.create(
        op.get_bind(),
        checkfirst=True,
    )

    op.create_table(
        "material_lots",
        sa.Column(
            "id",
            sa.UUID(),
            nullable=False,
        ),
        sa.Column(
            "lot_code",
            sa.String(length=100),
            nullable=False,
        ),
        sa.Column(
            "material_type",
            sa.String(length=50),
            nullable=False,
        ),
        sa.Column(
            "supplier_code",
            sa.String(length=100),
            nullable=False,
        ),
        sa.Column(
            "received_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )

    op.create_index(
        op.f("ix_material_lots_lot_code"),
        "material_lots",
        ["lot_code"],
        unique=True,
    )

    op.add_column(
        "pcb_units",
        sa.Column(
            "material_lot_id",
            sa.UUID(),
            nullable=True,
        ),
    )

    op.add_column(
        "pcb_units",
        sa.Column(
            "shift",
            shift_type_enum,
            server_default="DAY",
            nullable=False,
        ),
    )

    op.create_index(
        op.f("ix_pcb_units_material_lot_id"),
        "pcb_units",
        ["material_lot_id"],
        unique=False,
    )

    op.create_foreign_key(
        "fk_pcb_units_material_lot_id_material_lots",
        "pcb_units",
        "material_lots",
        ["material_lot_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
    "fk_pcb_units_material_lot_id_material_lots",
    "pcb_units",
    type_="foreignkey",
)
    op.drop_index(op.f('ix_pcb_units_material_lot_id'), table_name='pcb_units')
    op.drop_column('pcb_units', 'shift')
    op.drop_column('pcb_units', 'material_lot_id')
    op.drop_index(op.f('ix_material_lots_lot_code'), table_name='material_lots')
    op.drop_table('material_lots')
    shift_type_enum = sa.Enum(
        "DAY",
        "NIGHT",
        name="shift_type",
    )
    shift_type_enum.drop(
        op.get_bind(),
        checkfirst=True,
    )
    # ### end Alembic commands ###
