"""create quality measurements table

Revision ID: c325ae79a813
Revises: ff7a3d0f37ae
Create Date: 2026-08-24 09:32:50.382896

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c325ae79a813'
down_revision: Union[str, Sequence[str], None] = 'ff7a3d0f37ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quality_measurements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('process_event_id', sa.UUID(), nullable=False),
    sa.Column('metric_code', sa.String(length=80), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=30), nullable=False),
    sa.Column('lower_spec_limit', sa.Float(), nullable=True),
    sa.Column('upper_spec_limit', sa.Float(), nullable=True),
    sa.Column('is_within_spec', sa.Boolean(), nullable=True),
    sa.Column('measured_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('\n            lower_spec_limit IS NULL\n            OR upper_spec_limit IS NULL\n            OR lower_spec_limit <= upper_spec_limit\n            ', name='ck_quality_measurements_spec_limits'),
    sa.ForeignKeyConstraint(['process_event_id'], ['process_events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('process_event_id', 'metric_code', name='uq_quality_measurements_event_metric')
    )
    op.create_index(op.f('ix_quality_measurements_process_event_id'), 'quality_measurements', ['process_event_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_quality_measurements_process_event_id'), table_name='quality_measurements')
    op.drop_table('quality_measurements')
    # ### end Alembic commands ###
