"""create production orders table

Revision ID: c9ac8354e3b5
Revises: d7f5f50f7cfb
Create Date: 2026-08-21 10:38:40.379740

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9ac8354e3b5'
down_revision: Union[str, Sequence[str], None] = 'd7f5f50f7cfb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('production_orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('order_code', sa.String(length=50), nullable=False),
    sa.Column('product_code', sa.String(length=50), nullable=False),
    sa.Column('target_quantity', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PLANNED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='production_order_status'), nullable=False),
    sa.Column('planned_start_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('planned_end_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_start_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_end_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('target_quantity > 0', name='ck_production_orders_target_quantity_positive'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_production_orders_order_code'), 'production_orders', ['order_code'], unique=True)
    op.create_index(op.f('ix_production_orders_product_code'), 'production_orders', ['product_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_production_orders_product_code'), table_name='production_orders')
    op.drop_index(op.f('ix_production_orders_order_code'), table_name='production_orders')
    op.drop_table('production_orders')
    # ### end Alembic commands ###
