"""create quality alerts table

Revision ID: cbd9b869c4d3
Revises: 9be507e2c74b
Create Date: 2026-09-07 14:11:45.872234

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cbd9b869c4d3'
down_revision: Union[str, Sequence[str], None] = '9be507e2c74b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quality_alerts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('rule_code', sa.String(length=50), nullable=False),
    sa.Column('dataset_prefix', sa.String(length=100), nullable=False),
    sa.Column('quality_date', sa.Date(), nullable=False),
    sa.Column('evaluated_count', sa.Integer(), nullable=False),
    sa.Column('issue_count', sa.Integer(), nullable=False),
    sa.Column('threshold_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('minimum_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('acknowledged_by_id', sa.UUID(), nullable=True),
    sa.CheckConstraint('acknowledged_by_id IS NULL OR acknowledged_at IS NOT NULL', name='ck_quality_alert_acknowledgement'),
    sa.CheckConstraint('evaluated_count > 0', name='ck_quality_alert_evaluated_positive'),
    sa.CheckConstraint('issue_count >= 0 AND issue_count <= evaluated_count', name='ck_quality_alert_issue_count'),
    sa.CheckConstraint('minimum_count > 0', name='ck_quality_alert_minimum_positive'),
    sa.CheckConstraint('threshold_percent >= 0 AND threshold_percent <= 100', name='ck_quality_alert_threshold'),
    sa.ForeignKeyConstraint(['acknowledged_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rule_code', 'dataset_prefix', 'quality_date', name='uq_quality_alert_rule_dataset_date')
    )
    op.create_index(op.f('ix_quality_alerts_quality_date'), 'quality_alerts', ['quality_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_quality_alerts_quality_date'), table_name='quality_alerts')
    op.drop_table('quality_alerts')
    # ### end Alembic commands ###
