"""create machines table

Revision ID: d7f5f50f7cfb
Revises: 
Create Date: 2026-08-20 13:08:46.337331

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7f5f50f7cfb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('machines',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('machine_code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('stage_type', sa.Enum('SOLDER_PASTE_PRINTING', 'COMPONENT_PLACEMENT', 'REFLOW_SOLDERING', 'AOI_INSPECTION', 'FUNCTIONAL_TESTING', name='stage_type'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'MAINTENANCE', 'OFFLINE', name='machine_status'), nullable=False),
    sa.Column('commissioned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_machines_machine_code'), 'machines', ['machine_code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_index(
        op.f("ix_machines_machine_code"),
        table_name="machines",
    )
    op.drop_table("machines")

    sa.Enum(
        name="machine_status",
    ).drop(
        op.get_bind(),
        checkfirst=True,
    )

    sa.Enum(
        name="stage_type",
    ).drop(
        op.get_bind(),
        checkfirst=True,
    )
