"""create process events table

Revision ID: ff7a3d0f37ae
Revises: 43225ffdf58e
Create Date: 2026-08-24 08:06:02.959455

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ff7a3d0f37ae'
down_revision: Union[str, Sequence[str], None] = '43225ffdf58e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('process_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pcb_unit_id', sa.UUID(), nullable=False),
    sa.Column('machine_id', sa.UUID(), nullable=False),
    sa.Column('result', sa.Enum('PENDING', 'PASSED', 'WARNING', 'FAILED', name='process_event_result'), nullable=False),
    sa.Column('process_parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['pcb_unit_id'], ['pcb_units.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_process_events_machine_id'), 'process_events', ['machine_id'], unique=False)
    op.create_index('ix_process_events_pcb_started_at', 'process_events', ['pcb_unit_id', 'started_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_index(
        "ix_process_events_pcb_started_at",
        table_name="process_events",
    )
    op.drop_index(
        op.f("ix_process_events_machine_id"),
        table_name="process_events",
    )
    op.drop_table("process_events")

    sa.Enum(
        name="process_event_result",
    ).drop(
        op.get_bind(),
        checkfirst=True,
    )
    # ### end Alembic commands ###
